version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: zenla-mart-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: zenla
      POSTGRES_PASSWORD: zenla_secret
      POSTGRES_DB: zenla_mart
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
