import Footer from "@/component/Footer.jsx";
import "./globals.css";
import Header from "@/component/Header.jsx";
import { Providers } from "@/component/Providers.jsx";

import { Inter } from "next/font/google";
import ThemeProvider from "@/context/ThemeContext";
import { NotificationProvider } from "@/context/NotificationProvider";
import ErrorHandler from "@/component/ErrorHandler.jsx";
import ScrollObserver from "@/component/ScrollObserver.jsx";


const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "Zenla Mart Aplication with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ErrorHandler />
        <Providers>
          <NotificationProvider>
            <ThemeProvider>
              <Header />
              <ScrollObserver />
              {children}
              <Footer />
            </ThemeProvider>
          </NotificationProvider>
        </Providers>
      </body>
    </html>
  );
}
