import Footer from "@/component/Footer.jsx";
import "./globals.css";
import Header from "@/component/Header.jsx";

import { Inter } from "next/font/google";
import ThemeProvider from "@/context/ThemeContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Zenla Mart Aplication with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
